language: cpp

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  - wget -O Qt5.2.0.tar.xz http://thunderk.net/public/Qt5.2.0.tar.xz
  - mkdir ~/Qt5.2.0
  - tar -xJf Qt5.2.0.tar.xz -C ~/Qt5.2.0
  - sudo chmod -R 777 ~/Qt5.2.0/
  - make BUILDMODE=debug QTSDK=~/Qt5.2.0/5.2.0/gcc_64

script: make BUILDMODE=debug QTSDK=~/Qt5.2.0/5.2.0/gcc_64 tests
