language: cpp

before_script:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:beineri/opt-qt542 -y
    - sudo apt-get update -qq
    - sudo apt-get install g++-4.9 qt54base qt54quickcontrols qt54tools
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
    - source /opt/qt54/bin/qt54-env.sh && make BUILDMODE=debug

script:
    - source /opt/qt54/bin/qt54-env.sh && make BUILDMODE=debug tests

